apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-dind
spec:
  serviceAccountName: ecr-access-sa
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
    - name: docker-sock
      emptyDir: {}
  containers:
    - name: dind-daemon
      image: docker:26-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
        - name: docker-sock
          mountPath: /var/run

    - name: ubuntu-container
      image: ubuntu:latest
      securityContext:
        privileged: true
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -ex
          apt-get update && apt-get install -y curl unzip git docker.io

          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip && ./aws/install

          # Clone private GitHub repo using token
          git clone https://{{TOKEN}}@github.com/ncats/deployments.git
          cp deployments/jenkins/nginx/*.conf deployments/
          cd deployments/

          
          # Login to ECR and build Docker image
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{DOCKER_REPO_NAME}}
          docker build --no-cache --build-arg BUILD_VERSION={{BUILD_VERSION}} -t {{DOCKER_REPO_NAME}} .
          docker tag {{DOCKER_REPO_NAME}}:latest {{DOCKER_REPO_NAME}}:{{BUILD_VERSION}}
          docker push {{DOCKER_REPO_NAME}}:{{BUILD_VERSION}}

          exit 0
